# Generated by Django 3.2.9 on 2024-12-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0026_auto_20221205_0216'),
    ]

    operations = [
    ]
