# Generated by Django 3.2.9 on 2024-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0027_auto_20241226_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='nombramiento_encargado_convivencia',
            field=models.FileField(blank=True, null=True, upload_to='nombramiento_encargado_convivencia/'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='plan_gestion_convivencia',
            field=models.FileField(blank=True, null=True, upload_to='plan_gestion_convivencia/'),
        ),
    ]
