# Generated by Django 3.2.9 on 2024-12-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pise', '0029_protocoloinstitucional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connotacionsexual',
            name='tipo_connotacion_sexual',
        ),
        migrations.AlterField(
            model_name='connotacionsexual',
            name='estado',
            field=models.CharField(choices=[('nol', 'No leído'), ('ong', 'En gestión')], default='nol', max_length=3),
        ),
        migrations.AlterField(
            model_name='establecimiento',
            name='rbd',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pise.establecimiento', to_field='rbd'),
        ),
    ]
